# Generated by Django 4.0.3 on 2022-04-14 22:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DncNumber',
            fields=[
                ('dnc_number', models.CharField(max_length=20)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnccore.vendor')),
            ],
        ),
    ]
